# Regular Leco model configuration file
configuration_file = "configuration_exp2.toml"

# Template to use for generating output directory pathnames. All variable parameters must be mentioned.
directory_pattern = "/experiment_2/speed_{speed}/mutation_rate_{mutation_rate}/radius_{radius}/diffusion_rate_{diffusion_rate}/similarity_preference_{similarity_preference}/seed_{seed}"

[sensitivity.run]
# Section with settings for performing a sensitivity analysis
method = "ofat" # One factor at a time

[sensitivity.run.initialization]
seed.range = [44, 45, 1]

[sensitivity.run.movement]
speed.range = [0, 32.5, 2.5]

[sensitivity.run.language]
mutation_rate.range = [0.0, 0.0001625, 0.0000125]

[sensitivity.run.interaction]
radius.range = [0.0, 162.5, 12.5]
diffusion_rate.range = [0.0, 0.455, 0.035]
similarity_preference.range = [-1.0, 1.2, 0.2]
