#!/bin/bash

# Set up environment
./create_environment.sh

## Experiment 1
# Run the baseline for different seed values
seeds=(42 43 44 45 46)
for seed in seeds; do
  directory="/experiment_1/seed_$seed"
  ./run_cluster_plot.sh /directory
done

# Analyze output
./analyze_baseline.sh
